In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/amazon_sales_data_uncleaned.csv")

In [2]:
df.head()

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,21-08-2025 11:14
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,21-08-2025 11:14

In [3]:
df.tail()

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,30-08-2025 19:56
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,30-08-2025 19:56
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,30-08-2025 19:56
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,30-08-2025 19:56
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,30-08-2025 19:56

In [4]:
df.shape

(42675, 16)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Title                     42675 non-null  object
 1   Rating                    41651 non-null  object
 2   Number_of_reviews         41651 non-null  object
 3   bought_in_last_month      39458 non-null  object
 4   Current/discounted_price  30926 non-null  object
 5   Price_on_variant          42675 non-null  object
 6   Listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      28022 non-null  object
 11  delivery_details          30955 non-null  object
 12  sustainability_badges     3408 non-null   object
 13  image_url                 42675 non-null  object
 14  product_url               40606 non-null  object
 15  collected_at              42675 non-null  object
dtypes: object(16)
memory usage: 5.2+ MB

In [6]:
df.columns

Index(['Title', 'Rating', 'Number_of_reviews', 'bought_in_last_month',
       'Current/discounted_price', 'Price_on_variant', 'Listed_price',
       'is_best_seller', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'sustainability_badges', 'image_url', 'product_url',
       'collected_at'],
      dtype='object')

In [7]:
df.describe()

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
count,42675,41651,41651,39458,30926,42675,42675,42675,42675,42675,28022,30955,3408,42675,40606,42675
unique,8808,31,4413,59,2576,3466,911,12,2,42,1,298,16,8038,40606,331
top,"Duracell Coppertop 9V Battery, 6 Count (Pack o...",4.6 out of 5 stars,25,100+ bought in past month,29.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,Add to cart,"Delivery Mon, Sep 1",Small Business,https://m.media-amazon.com/images/I/51Xr76m2WL...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,25-08-2025 11:07
freq,744,6151,626,8801,825,21031,30364,40814,35664,40727,28022,6189,1341,1461,1,180

In [8]:
df.dtypes

Title                       object
Rating                      object
Number_of_reviews           object
bought_in_last_month        object
Current/discounted_price    object
Price_on_variant            object
Listed_price                object
is_best_seller              object
is_sponsored                object
is_couponed                 object
buy_box_availability        object
delivery_details            object
sustainability_badges       object
image_url                   object
product_url                 object
collected_at                object
dtype: object

In [9]:
df["Rating"].head(20)

0     4.6 out of 5 stars
1     4.3 out of 5 stars
2     4.6 out of 5 stars
3     4.6 out of 5 stars
4     4.8 out of 5 stars
5     4.6 out of 5 stars
6     4.5 out of 5 stars
7     4.6 out of 5 stars
8     4.0 out of 5 stars
9     4.7 out of 5 stars
10    4.7 out of 5 stars
11    4.8 out of 5 stars
12    4.2 out of 5 stars
13    4.4 out of 5 stars
14    4.7 out of 5 stars
15    4.7 out of 5 stars
16    4.8 out of 5 stars
17    4.7 out of 5 stars
18    4.8 out of 5 stars
19    4.6 out of 5 stars
Name: Rating, dtype: object

In [10]:
df["Rating"]=df["Rating"].str.extract(r"(\d+\.+\d+)")
df["Rating"]=df["Rating"].astype(float)

In [11]:
df["Rating"].count()

np.int64(41651)

In [12]:
df["Rating"].isnull().sum()

np.int64(1024)

In [13]:
df["Number_of_reviews"].isnull().sum()

np.int64(1024)

In [14]:
df[df["Rating"]>4.5]

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,"3,044",2K+ bought in past month,314,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,21-08-2025 11:14
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,21-08-2025 11:14
5,Texas Instruments TI-84 Plus CE Color Graphing...,4.6,"44,522",100K+ bought in past month,NaN,basic variant price: $99.95,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/71AyPChhFd...,/Texas-Instruments-TI-84-Graphing-Calculator/d...,21-08-2025 11:14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42664,PGYTECH CreateMate High-Speed SD Card Reader U...,4.6,"1,202",300+ bought in past month,35.96,basic variant price: nan,$39.95,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",Carbon impact,https://m.media-amazon.com/images/I/61Up6EZG9h...,/PGYTECH-CreateMate-High-Speed-Carrying-Smartp...,30-08-2025 19:56
42665,Sprayground PACMAN GHOST GANG SHARMOUTH,4.9,19,300+ bought in past month,NaN,basic variant price: $126.70,No Discount,No Badge,Organic,No Coupon,NaN,NaN,Small Business,https://m.media-amazon.com/images/I/61ruhT+eIc...,/Sprayground-PACMAN-GHOST-GANG-SHARMOUTH/dp/B0...,30-08-2025 19:56
42668,GE 3-Outlet Power Strip Surge Protector 15 Ft ...,4.8,"20,356",500+ bought in past month,12.23,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/819uTFhmSQ...,/GE-Designer-Extension-Protection-44237/dp/B07...,30-08-2025 19:56
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,30-08-2025 19:56
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,30-08-2025 19:56

In [15]:
df["bought_in_last_month"] = df["bought_in_last_month"].astype(str)

# Remove common suffixes like "+ bought in past month" and any optional leading "+"
df["bought_in_last_month"] = df["bought_in_last_month"].str.replace(r"\s*\+?\s*bought in past month", "", regex=True)

def convert_bought(value):
    value = str(value).strip()

    # Handle cases like 'nan' strings or empty strings after cleaning
    if not value or value.lower() == 'nan':
        return np.nan

    # Handle 'K' for thousands
    if "K" in value:
        value = value.replace("K", "")
        # Use pd.to_numeric with errors='coerce' to turn unparseable values into NaN
        return pd.to_numeric(value, errors='coerce') * 1000
    else:
        # For other numeric strings, convert directly
        return pd.to_numeric(value, errors='coerce')

df["bought_in_last_month"] = df["bought_in_last_month"].apply(convert_bought)
df["bought_in_last_month"].head(220)

0        300.0
1       6000.0
2       2000.0
3      10000.0
4      10000.0
        ...
215     4000.0
216    10000.0
217     7000.0
218    10000.0
219      500.0
Name: bought_in_last_month, Length: 220, dtype: float64

In [16]:
df['bought_in_last_month']

0          300.0
1         6000.0
2         2000.0
3        10000.0
4        10000.0
          ...
42670      100.0
42671      200.0
42672       50.0
42673      500.0
42674       50.0
Name: bought_in_last_month, Length: 42675, dtype: float64

In [17]:
df["Listed_price"]=df["Listed_price"].replace("No discount",np.nan)

In [18]:
df["Listed_price"] = (
    df["Listed_price"]
    .str.replace("$", "", regex=False)
)
df["Listed_price"] = (
    df["Listed_price"]
    .str.replace(",", "", regex=False)
)

In [19]:
df["Listed_price"] = pd.to_numeric(
    df["Listed_price"],
    errors="coerce"
)

In [20]:
df["is_best_seller"] = (
    df["is_best_seller"] == "Best Seller"
)
df["is_best_seller"].dtype

dtype('bool')

In [21]:
df["is_sponsored"] = df["is_sponsored"] == "Sponsored"
df["is_sponsored"].dtype

dtype('bool')

In [22]:
df["is_couponed"] = df["is_couponed"] != "No Coupon"

In [23]:
df["collected_at"] = pd.to_datetime(
    df["collected_at"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

In [24]:
df.isnull().sum()

Title                           0
Rating                       1024
Number_of_reviews            1024
bought_in_last_month        10511
Current/discounted_price    11749
Price_on_variant                0
Listed_price                30364
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
image_url                       0
product_url                  2069
collected_at                    0
dtype: int64

In [25]:
df["Rating"].isna().sum()

np.int64(1024)

In [26]:
df["Rating"].mean()

np.float64(4.3994309860507546)

In [27]:
df[df["Number_of_reviews"].isna()].head()

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
854,Buffalo Games - Gold - Eric Dowdle - Golden Ga...,NaN,NaN,50.0,12,basic variant price: nan,NaN,False,True,False,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/81IhN+yhrY...,/sspa/click?ie=UTF8&spc=MTo0MzMzMTM1MzExOTMwNj...,2025-08-21 11:21:00
1857,"Lenovo ThinkPad X1 Carbon Gen 13 Aura Edition,...",NaN,NaN,200.0,"2,098.00","basic variant price: $1,895.00",2549.00,False,False,False,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61JZTWfKMR...,/Lenovo-ThinkPad-Carbon-Intel-Camera/dp/B0DQ4C...,2025-08-21 11:28:00
2599,FEELWORLD F7 Plus Camera Field Touchscreen Mon...,NaN,NaN,NaN,165,basic variant price: nan,NaN,False,True,False,Add to cart,Delivery Aug 29 - Sep 2,NaN,https://m.media-amazon.com/images/I/717PLQhkhK...,/sspa/click?ie=UTF8&spc=MTo0MjY2ODkzNzQ4MzA2MT...,2025-08-21 11:33:00
2600,FEELWORLD P6XL Camera Field Touchscreen Monito...,NaN,NaN,NaN,165,basic variant price: nan,199.00,False,True,False,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/714Z4DIJDM...,/sspa/click?ie=UTF8&spc=MTo0MjY2ODkzNzQ4MzA2MT...,2025-08-21 11:33:00
3481,FEELWORLD 4K10X PTZ Camera 4K Resolution 10X U...,NaN,NaN,NaN,299.99,basic variant price: nan,369.99,False,True,False,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61AL4I0eBx...,/sspa/click?ie=UTF8&spc=MTo1NDA3NTc1Njk1MDMwMj...,2025-08-21 11:40:00

In [28]:
df["bought_in_last_month"].fillna(0)

0          300.0
1         6000.0
2         2000.0
3        10000.0
4        10000.0
          ...
42670      100.0
42671      200.0
42672       50.0
42673      500.0
42674       50.0
Name: bought_in_last_month, Length: 42675, dtype: float64

In [29]:

df[df["Current/discounted_price"].isna()][
    ["Title", "Price_on_variant", "Listed_price"]
].head(20)

,Title,Price_on_variant,Listed_price
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",basic variant price: $162.24,NaN
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,basic variant price: $72.74,NaN
5,Texas Instruments TI-84 Plus CE Color Graphing...,basic variant price: $99.95,NaN
6,"Apple AirPods 4 Wireless Earbuds, Bluetooth He...",basic variant price: $88.11,NaN
7,Apple AirTag. Keep Track of and find Your Keys...,basic variant price: $23.04,NaN
9,"Apple iPad 11-inch: A16 chip, 11-inch Model, L...",basic variant price: $284.05,NaN
11,Apple 2025 MacBook Air 13-inch Laptop with M4 ...,basic variant price: $880.95,NaN
15,Texas Instruments TI-30XIIS Scientific Calcula...,basic variant price: $17.45,NaN
19,Roku Streaming Stick HD 2025 — HD Streaming De...,basic variant price: $33.51,NaN
21,Apple Watch SE (2nd Gen) [GPS 40mm] Smartwatch...,basic variant price: $146.14,NaN
23,"Apple EarPods Headphones with USB-C Plug, Wire...",basic variant price: $16.10,NaN
24,Duracell 2032 Lithium Battery. 4 Count Pack. C...,basic variant price: 4 Count,NaN
27,"Sony ZX Series Wired On-Ear Headphones, Black ...",basic variant price: $9.54,NaN
28,HP 67 Black/Tri-color Ink Cartridges for HP Pr...,basic variant price: $43.89,NaN
29,HP 67XL Black High-yield Ink Cartridge | Works...,basic variant price: $35.89,NaN
36,"Energizer Ultimate Lithium AA Batteries Pack, ...",basic variant price: 24 Count (Pack of 1),NaN
38,JBL Vibe Beam - True Wireless JBL Deep Bass So...,basic variant price: $29.95,NaN
39,Apple Pencil Pro: Latest Model - Device Compat...,basic variant price: $148.00,NaN
47,Apple Watch Series 10 [GPS 42mm case] Smartwat...,basic variant price: $280.12,NaN
52,Beats Solo 4 - Wireless Bluetooth On-Ear Headp...,basic variant price: $127.49,NaN

In [30]:
df["has_listed_price"] = df["Listed_price"].notna()

In [31]:
df[
    ["is_best_seller", "is_sponsored", "is_couponed"]
].isnull().sum()

is_best_seller    0
is_sponsored      0
is_couponed       0
dtype: int64

In [32]:
df["buy_box_availability"].value_counts(dropna=False)

buy_box_availability
Add to cart    28022
NaN            14653
Name: count, dtype: int64

In [33]:
df["delivery_details"] = (
    df["delivery_details"].fillna("Unknown")
)

In [34]:
df["has_sustainability_badge"] = (
    df["sustainability_badges"].notna()
)

In [35]:
df = df.drop(columns=["sustainability_badges"])

In [36]:
missing = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": df.isnull().mean() * 100
})

missing.sort_values(
    "missing_percentage",
    ascending=False
)

                          missing_count  missing_percentage
Listed_price                      30364           71.151728
buy_box_availability              14653           34.336262
Current/discounted_price          11749           27.531342
bought_in_last_month              10511           24.630346
product_url                        2069            4.848272
Rating                             1024            2.399531
Number_of_reviews                  1024            2.399531
Title                                 0            0.000000
Price_on_variant                      0            0.000000
is_sponsored                          0            0.000000
is_best_seller                        0            0.000000
delivery_details                      0            0.000000
is_couponed                           0            0.000000
image_url                             0            0.000000
collected_at                          0            0.000000
has_listed_price                      0            0.000000
has_sustainability_badge              0            0.000000

In [37]:
df[df["Rating"].isna()].head()

df[df["Number_of_reviews"].isna()].head()

df[df["bought_in_last_month"].isna()].head()

df[df["Current/discounted_price"].isna()].head()

df[df["buy_box_availability"].isna()].head()

df[df["delivery_details"].isna()].head()

df[df["product_url"].isna()].head()

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,image_url,product_url,collected_at,has_listed_price,has_sustainability_badge
20,"Energizer AA Batteries Alkaline Power, 32 Coun...",4.8,"61,157",100000.0,16.95,basic variant price: $16.78,19.98,False,False,False,Add to cart,"Delivery Fri, Aug 29",https://m.media-amazon.com/images/I/91-R5huHLn...,NaN,2025-08-21 11:14:00,True,False
24,Duracell 2032 Lithium Battery. 4 Count Pack. C...,4.7,"84,821",100000.0,NaN,basic variant price: 4 Count,NaN,True,False,False,NaN,Unknown,https://m.media-amazon.com/images/I/71B7wnkW7D...,NaN,2025-08-21 11:14:00,False,False
25,"Energizer Alkaline Power AAA Batteries, 32 Cou...",4.8,"43,002",70000.0,15.15,basic variant price: $14.77,17.99,False,False,False,Add to cart,"Delivery Fri, Aug 29",https://m.media-amazon.com/images/I/91ass+ZYjc...,NaN,2025-08-21 11:14:00,True,False
26,Duracell Coppertop AA Batteries with Power Boo...,4.8,"1,25,404",80000.0,18.79,basic variant price: 24 Count (Pack of 1),21.89,False,False,False,Add to cart,"Delivery Fri, Aug 29",https://m.media-amazon.com/images/I/71F1yxjGeY...,NaN,2025-08-21 11:14:00,True,False
36,"Energizer Ultimate Lithium AA Batteries Pack, ...",4.7,"32,810",40000.0,NaN,basic variant price: 24 Count (Pack of 1),NaN,False,False,False,NaN,Unknown,https://m.media-amazon.com/images/I/71eW3rQCd6...,NaN,2025-08-21 11:14:00,False,False

In [38]:
df[df["Rating"].isna()].head()

df[df["Number_of_reviews"].isna()].head()

df[df["bought_in_last_month"].isna()].head()

df[df["Current/discounted_price"].isna()].head()

df[df["buy_box_availability"].isna()].head()

df[df["delivery_details"].isna()].head()

df[df["product_url"].isna()].head()

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,image_url,product_url,collected_at,has_listed_price,has_sustainability_badge
20,"Energizer AA Batteries Alkaline Power, 32 Coun...",4.8,"61,157",100000.0,16.95,basic variant price: $16.78,19.98,False,False,False,Add to cart,"Delivery Fri, Aug 29",https://m.media-amazon.com/images/I/91-R5huHLn...,NaN,2025-08-21 11:14:00,True,False
24,Duracell 2032 Lithium Battery. 4 Count Pack. C...,4.7,"84,821",100000.0,NaN,basic variant price: 4 Count,NaN,True,False,False,NaN,Unknown,https://m.media-amazon.com/images/I/71B7wnkW7D...,NaN,2025-08-21 11:14:00,False,False
25,"Energizer Alkaline Power AAA Batteries, 32 Cou...",4.8,"43,002",70000.0,15.15,basic variant price: $14.77,17.99,False,False,False,Add to cart,"Delivery Fri, Aug 29",https://m.media-amazon.com/images/I/91ass+ZYjc...,NaN,2025-08-21 11:14:00,True,False
26,Duracell Coppertop AA Batteries with Power Boo...,4.8,"1,25,404",80000.0,18.79,basic variant price: 24 Count (Pack of 1),21.89,False,False,False,Add to cart,"Delivery Fri, Aug 29",https://m.media-amazon.com/images/I/71F1yxjGeY...,NaN,2025-08-21 11:14:00,True,False
36,"Energizer Ultimate Lithium AA Batteries Pack, ...",4.7,"32,810",40000.0,NaN,basic variant price: 24 Count (Pack of 1),NaN,False,False,False,NaN,Unknown,https://m.media-amazon.com/images/I/71eW3rQCd6...,NaN,2025-08-21 11:14:00,False,False

In [39]:
missing = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percentage": df.isna().mean() * 100
})

missing.sort_values(
    "missing_percentage",
    ascending=False
)

                          missing_count  missing_percentage
Listed_price                      30364           71.151728
buy_box_availability              14653           34.336262
Current/discounted_price          11749           27.531342
bought_in_last_month              10511           24.630346
product_url                        2069            4.848272
Rating                             1024            2.399531
Number_of_reviews                  1024            2.399531
Title                                 0            0.000000
Price_on_variant                      0            0.000000
is_sponsored                          0            0.000000
is_best_seller                        0            0.000000
delivery_details                      0            0.000000
is_couponed                           0            0.000000
image_url                             0            0.000000
collected_at                          0            0.000000
has_listed_price                      0            0.000000
has_sustainability_badge              0            0.000000

In [40]:
missing = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percentage": df.isna().mean() * 100
})

missing.sort_values(
    "missing_percentage",
    ascending=False
)

                          missing_count  missing_percentage
Listed_price                      30364           71.151728
buy_box_availability              14653           34.336262
Current/discounted_price          11749           27.531342
bought_in_last_month              10511           24.630346
product_url                        2069            4.848272
Rating                             1024            2.399531
Number_of_reviews                  1024            2.399531
Title                                 0            0.000000
Price_on_variant                      0            0.000000
is_sponsored                          0            0.000000
is_best_seller                        0            0.000000
delivery_details                      0            0.000000
is_couponed                           0            0.000000
image_url                             0            0.000000
collected_at                          0            0.000000
has_listed_price                      0            0.000000
has_sustainability_badge              0            0.000000

In [42]:
import os

# Create the 'data' directory if it doesn't exist
if not os.path.exists('data'):
    os.makedirs('data')

df.to_csv(
    "data/amazon_sales_data_cleaned.csv",
    index=False
)